### ISSUE TITLE
Is it possible to add freeform extra yaml headers? 1/2

### ISSUE THREAD

**Issue by yefeiyu** [ardumont/org2jekyll#34]
add it into org2jekyll.el, and it can use when org file export to html file.

```yaml
---
layout: post
title: Custom Color Scheme
category: note
tags: curtana
scheme-text: "#0029ff"         <<<--here
scheme-link: "#ff00b4"                  ...
scheme-hover: "#ff00b4"               ...
scheme-code: "#ad00ff"                ...
scheme-bg: "#00ebff"                   ...
scheme-hero-text: "#00ebff"         ...
scheme-hero-link: "#00ebff"         ...
scheme-hero-bg: "#0029ff"          ...
plugin: lightense                         ---until here>>>
---
```

I use the Super-fast Jekyll framework for Github blog, Almace Scaffolding. It need this Markdown Head.
the address is :
http://sparanoid.com/lab/amsf/

Thank you for your help!
